### ISSUE TITLE
`Df_Localization_Model_Realtime_Dictionary->hasEntry('Empty')`: «Parsing a JSON document failed with the message «Syntax error»»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento-russia/2#14]
```
Parsing a JSON document failed with the message «Syntax error».
The document:


#0 app\code\local\Df\Core\lib\fp\serialize.php(68): df_error('Parsing a JSON ...', 'Syntax error')
#1 app\code\local\Df\Localization\Model\Realtime\Dictionary.php(336): df_json_decode(false)
#2 app\code\local\Df\Localization\Model\Realtime\Dictionary.php(32): Df_Localization_Model_Realtime_Dictionary->hasEntry('Empty')
#3 app\code\local\Df\Localization\Model\Realtime\Translator.php(46): Df_Localization_Model_Realtime_Dictionary->translate('Empty', 'Mage_Page::Empt...')
#4 app\code\local\Df\Core\Model\Translate.php(416): Df_Localization_Model_Realtime_Translator->translate('Empty', 'Mage_Page::Empt...')
#5 app\code\core\Mage\Core\Model\Translate.php(401): Df_Core_Model_Translate->_getTranslatedString('Empty', 'Mage_Page::Empt...')
#6 app\code\core\Mage\Core\Helper\Abstract.php(186): Mage_Core_Model_Translate->translate(Array)
#7 app\code\core\Mage\Page\Model\Config.php(77): Mage_Core_Helper_Abstract->__('Empty')
#8 app\code\core\Mage\Page\Model\Config.php(56): Mage_Page_Model_Config->_appendPageLayouts('global/page/lay...')
#9 app\code\core\Mage\Page\Model\Config.php(106): Mage_Page_Model_Config->_initPageLayouts()
#10 app\code\core\Mage\Page\Helper\Layout.php(44): Mage_Page_Model_Config->getPageLayout('one_column')
#11 app\code\core\Mage\Cms\Helper\Page.php(104): Mage_Page_Helper_Layout->applyHandle('one_column')
#12 app\code\core\Mage\Cms\Helper\Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'home')
#13 app\code\core\Mage\Cms\controllers\IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'home')
#14 app\code\core\Mage\Core\Controller\Varien\Action.php(418): Mage_Cms_IndexController->indexAction()
#15 app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#16 app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 app\Mage.php(683): Mage_Core_Model_App->run(Array)
#19 index.php(93): Mage::run('', 'store')
#20 {main}
```

**Comment by dmitrii-fediuk** [comment]
Исправлено в версии [2.51.3](https://github.com/magento-russia/2/releases/tag/2.51.3).
