### ISSUE TITLE
«Call to a member function setSkipRenderTag() on boolean in Df/PageCache/Model/Container/Minicart.php:13»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento-russia/2#2]
```
#0 app/code/local/Df/PageCache/Model/Container/Abstract.php(81): Df_PageCache_Model_Container_Minicart->_renderBlock()
#1 app/code/local/Df/PageCache/controllers/RequestController.php(14): Df_PageCache_Model_Container_Abstract-&gt;applyInApp('/r/n&lt;!DOCTYPE htm...')
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Df_PageCache_RequestController-&gt;processAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('process')
#4 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 app/code/core/M in <b>app/code/local/Df/PageCache/Model/Container/Minicart.php</b> on line <b>13</b>
```

**Comment by dmitrii-fediuk** [comment]
Исправлено в версии [2.50.1](https://github.com/magento-russia/2/releases/tag/2.50.1).
